name: 'Safe Action Debugger'
description: 'Protected interactive debugger for GitHub Actions with tmate.io. Docker supported.'
runs:
  using: 'node12'
  main: 'action.js'
branding:
  icon: 'terminal'
  color: 'green'
